version: "3"

services:
  merit-kapital:
    container_name: betpawa__mysql
    image: mysql:5
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=betpawa_root
      - MYSQL_DATABASE=betpawa
      - MYSQL_USER=betpawa_user
      - MYSQL_PASSWORD=betpawa_pass
    networks:
      - cmnet

networks:
  cmnet:
    driver: bridge
